#!/bin/bash                                                                                                                                                                                                                                                                                                                                                 
#                                                                                                                                                                                                                                                                                                                                                           
# crontab -l > mycron                                                                                                                                                                                                                                                                                                                                       
# echo "#" >> mycron                                                                                                                                                                                                                                                                                                                                        
# echo "# At every 2nd minute" >> mycron                                                                                                                                                                                                                                                                                                                    
# echo "*/1 * * * * /bin/bash /autofan.sh >> /tmp/cron.log" >> mycron                                                                                                                                                                                                                                                                                       
# crontab mycron                                                                                                                                                                                                                                                                                                                                            
# rm mycron                                                                                                                                                                                                                                                                                                                                                 
# chmod +x /autofan.sh                                                                                                                                                                                                                                                                                                                                      
#                                                                                                                                                                                                                                                                                                                                                           
PASSWORD=""                                                                                                                                                                                                                                                                                                                             
USERNAME=""                                                                                                                                                                                                                                                                                                                                               
ILOIP=""                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                            
#T1="$(sensors -Aj coretemp-isa-0000 | jq '.[][] | to_entries[] | select(.key | endswith("input")) | .value' | sort -rn | head -n1)"                                                                                                                                                                                                                        
#T2="$(sensors -Aj coretemp-isa-0001 | jq '.[][] | to_entries[] | select(.key | endswith("input")) | .value' | sort -rn | head -n1)"                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                            
#CPU 3                                                                                                                                                                                                                                                                                                                                                      
sshpass -p $PASSWORD ssh $USERNAME@$ILOIP show /system1/sensor2 > temp.txt                                                                                                                                                                                                                                                                                  
T1CLEAN=$(grep --color=never -Ihr "CurrentReading" temp.txt | xargs -d '\r')                                                                                                                                                                                                                                                                                
T1=$(echo "${T1CLEAN/    CurrentReading=/}" | xargs)                                                                                                                                                                                                                                                                                                        
rm -rf temp.txt                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                            
#CPU 2                                                                                                                                                                                                                                                                                                                                                      
sshpass -p $PASSWORD ssh $USERNAME@$ILOIP show /system1/sensor3 > temp.txt                                                                                                                                                                                                                                                                                  
T2CLEAN=$(grep --color=never -Ihr "CurrentReading" temp.txt | xargs -d '\r')                                                                                                                                                                                                                                                                                
T2=$(echo "${T2CLEAN/    CurrentReading=/}" | xargs)                                                                                                                                                                                                                                                                                                        
rm -rf temp.txt                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                            
#RAID Controller                                                                                                                                                                                                                                                                                                                                            
sshpass -p $PASSWORD ssh $USERNAME@$ILOIP show /system1/sensor25 > temp.txt                                                                                                                                                                                                                                                                                 
T3CLEAN=$(grep --color=never -Ihr "CurrentReading" temp.txt | xargs -d '\r')                                                                                                                                                                                                                                                                                
T3=$(echo "${T3CLEAN/    CurrentReading=/}" | xargs)                                                                                                                                                                                                                                                                                                        
rm -rf temp.txt                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            
date                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            
echo "==============="                                                                                                                                                                                                                                                                                                                                      
echo "CPU 1 Temp $T1 C"                                                                                                                                                                                                                                                                                                                                     
echo "==============="                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                            
if [[ $T1 > 67 ]]                                                                                                                                                                                                                                                                                                                                           
   then                                                                                                                                                                                                                                                                                                                                                     
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 125' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 125' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 125' &> /dev/null                                                                                                                                                                                                                                                                            
elif [[ $T1 > 58 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 100' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 100' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 100' &> /dev/null                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            
elif [[ $T1 > 54 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 80' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 80' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 80' &> /dev/null                                                                                                                                                                                                                                                                             
elif [[ $T1 > 52 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 70' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 70' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 70' &> /dev/null                                                                                                                                                                                                                                                                             
elif [[ $T1 > 50 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 60' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 60' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 60' &> /dev/null                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                            
elif [[ $T1 > 48 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 55' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 55' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 55' &> /dev/null                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                            
elif [[ $T1 > 45 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 50' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 50' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 50' &> /dev/null                                                                                                                                                                                                                                                                             
elif [[ $T1 > 42 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 45' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 45' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 45' &> /dev/null                                                                                                                                                                                                                                                                             
else                                                                                                                                                                                                                                                                                                                                                        
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 40' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 40' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 40' &> /dev/null                                                                                                                                                                                                                                                                             
fi                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                            
echo "==============="                                                                                                                                                                                                                                                                                                                                      
echo "CPU 2 Temp $T2 C"                                                                                                                                                                                                                                                                                                                                     
echo "==============="                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                            
if [[ $T2 > 67 ]]                                                                                                                                                                                                                                                                                                                                           
   then                                                                                                                                                                                                                                                                                                                                                     
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 0 max 125' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 1 max 125' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 2 max 125' &> /dev/null                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            
elif [[ $T2 > 58 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 0 max 100' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 1 max 100' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 2 max 100' &> /dev/null                                                                                                                                                                                                                                                                            
elif [[ $T2 > 54 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 0 max 80' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 1 max 80' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 2 max 80' &> /dev/null                                                                                                                                                                                                                                                                             
elif [[ $T2 > 52 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 0 max 70' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 1 max 70' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 2 max 70' &> /dev/null                                                                                                                                                                                                                                                                             
elif [[ $T2 > 50 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 0 max 60' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 1 max 60' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 2 max 60' &> /dev/null                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                            
elif [[ $T1 > 48 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 0 max 50' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 1 max 50' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 2 max 50' &> /dev/null                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                            
elif [[ $T1 > 45 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 0 max 40' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 1 max 40' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 2 max 40' &> /dev/null                                                                                                                                                                                                                                                                             
elif [[ $T1 > 42 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 0 max 35' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 1 max 35' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 2 max 35' &> /dev/null                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                            
else                                                                                                                                                                                                                                                                                                                                                        
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 0 max 30' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 1 max 30' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 2 max 30' &> /dev/null                                                                                                                                                                                                                                                                             
fi                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                            
echo "==============="                                                                                                                                                                                                                                                                                                                                      
echo "RAID Temp $T3 C"                                                                                                                                                                                                                                                                                                                                      
echo "==============="                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                            
if [[ $T3 > 90 ]]                                                                                                                                                                                                                                                                                                                                           
   then                                                                                                                                                                                                                                                                                                                                                     
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 125' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 125' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 125' &> /dev/null                                                                                                                                                                                                                                                                            
elif [[ $T3 > 85 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 100' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 100' &> /dev/null                                                                                                                                                                                                                                                                            
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 100' &> /dev/null                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            
elif [[ $T3 > 80 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 80' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 80' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 80' &> /dev/null                                                                                                                                                                                                                                                                             
elif [[ $T3 > 75 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 75' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 70' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 75' &> /dev/null                                                                                                                                                                                                                                                                             
elif [[ $T3 > 70 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 60' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 65' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 70' &> /dev/null                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                            
elif [[ $T3 > 65 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 55' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 60' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 65' &> /dev/null                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                            
elif [[ $T3 > 60 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 50' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 55' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 60' &> /dev/null                                                                                                                                                                                                                                                                             
elif [[ $T3 > 55 ]]                                                                                                                                                                                                                                                                                                                                         
    then                                                                                                                                                                                                                                                                                                                                                    
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 45' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 50' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 55' &> /dev/null                                                                                                                                                                                                                                                                             
else                                                                                                                                                                                                                                                                                                                                                        
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 3 max 40' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 4 max 40' &> /dev/null                                                                                                                                                                                                                                                                             
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 5 max 50' &> /dev/null                                                                                                                                                                                                                                                                             
fi
